#! /usr/bin/node
//CONVERSION CHARTS
monthnumtoname = [
	"February",
	"March",
	"April",
	"May",
	"June",
	"July",
	"August",
	"September",
	"October",
	"November",
	"December"
];
const genderscitoname = {
	male: "Boy",
	female: "Girl"
};
const appearvartoname = {
	"eye-color":"Eye Color",
	"hair-color": "Hair Color",
	"hair-style":"Hair Style",
	"weight":"Weight",
	"height":"Height"
};

const fs = require('fs');
const path = require('path');
const args = process.argv.splice(2);
const action = args[0];
const date = new Date();
function nwconfigJSON(nw) {
	json = {}
	keys = []
	values = []
	nw.forEach(line => {
		keys.push(line.split(": ")[0])
		values.push(line.split(": ")[1])
	});
	for (let i = 0; i < nw.length; i++) {
		json[keys[i]] = values[i];
	}
	return json;
}
switch(action) {
    case 'new':
	
	/*if (ad.splice(1).includes("--help")){
                console.log("Usage: human new [name] [gender] <options>\nOptions:\n\t--apearence --- Adds appearence to a person via a .nwconfig file --- --appearence [file]\n\t--birth-override --- Replaces birthdate wirh specified date in mm/dd/yy --- --birth-overide [date]");
		process.exit();
        }*/
	if (args[1] && args[2]) {
	let cont = [];
        let name = args[1];
	cont.push("name: "+name);
	id = "";
	name.split("").forEach(char => {
		id += char.charCodeAt().toString(16);
	});
	cont.push("id: "+id);
	let birth = (date.getMonth()+1).toString()+"/"+(date.getDate()).toString()+"/"+date.getFullYear();
	cont.push("birth: "+birth);
	let gender = args[2];
	if (!["male", "female"].includes(gender)) {console.log(gender+" is not a gender");process.exit()}
	cont.push("gender: "+gender);
	const opts = args.splice(3);
	if (opts.includes("--appearence")) {
		let app = opts[opts.indexOf("--appearence") + 1]
		console.log("Loading Appearence from: "+app);
		if (!fs.existsSync(app)) {console.log("File "+app+" does not exist");process.exit()}
		let appearence = nwconfigJSON(fs.readFileSync(app,"utf8").split("\n"))
		cont.push("appearence: "+JSON.stringify(appearence));
	}
	if (opts.includes("--birth-override")) {
		let birex = /^\d{1,2}\/\d{1,2}\/\d{1,2}$/
		let bir = opts[opts.indexOf("--birth-override") + 1]
		if (!birex.test(bir)) {console.log(bir+" is not a date");process.exit()}
		cont[1] = "birth: "+bir;
	}
	console.log("writing to "+ name + ".human");
	fs.writeFileSync(name+".human", cont.join("\n"))
	} else {
		console.log("Arguments required: human new [name] [gender] <options>");
		process.exit();
	}
	break;
	case 'load':
		if (args[1]) {
			if (fs.existsSync(args[1])) {
				console.log("Loading human from file "+args[1])
				let nwhum = fs.readFileSync(args[1], "utf8");
				let jsonhum = nwconfigJSON(nwhum.split("\n"));
				console.log("Information on "+jsonhum.id)
				let datelist = jsonhum.birth.split("/");
				year = datelist[2];
				console.log(jsonhum.name+" was born on "+monthnumtoname[parseInt(datelist[0])-1] + " "+datelist[1]+", "+year);
				console.log(jsonhum.name + " is a "+genderscitoname[jsonhum.gender])
				if (jsonhum.appearence) {
					console.log("Appearence:")
					let appjson = JSON.parse(jsonhum.appearence);
					Object.keys(appjson).forEach(trait => {
						console.log(appearvartoname[trait]+": "+appjson[trait].replace("~", "about ").replace("lbs"," pounds"));
					});
				}
			}
		}
}
